

RESOURCES = ['storage','computing','bandwidth']
REQUEST_CLASSES = ['eMBB','mMTC','URLLC']
PRIORITY = False
DATASET_PATH = '../dataset/1_any_N1000_lambda10_mi5.pkl'


NUM_TIME_STEPS = 1000

EMBB_BASE_STORAGE = 5000
EMBB_BASE_COMPUTING = 5
EMBB_BASE_BAND = 2000

URLLC_BASE_STORAGE = 3000
URLLC_BASE_COMPUTING = 3
URLLC_BASE_BAND = 600

MMTC_BASE_STORAGE = 2000 
MMTC_BASE_COMPUTING = 2
MMTC_BASE_BAND = 160

#!Optimal and Fast Real-Time Resource Slicing (Huynh et al 2019)
INP_STORAGE = 50_000
INP_COMPUTING = 40
INP_BAND = 20_000 #2000


#For Normalization
MAX_VALS = {RESOURCES[0]:INP_STORAGE,RESOURCES[1]:INP_COMPUTING,RESOURCES[2]:INP_BAND}
#MAX_VALS = {RESOURCES[0]:EMBB_BASE_STORAGE*1.2,RESOURCES[1]:EMBB_BASE_COMPUTING*1.2,RESOURCES[2]:EMBB_BASE_BAND*1.2}
MIN_VALS = {RESOURCES[0]:MMTC_BASE_STORAGE*0.8,RESOURCES[1]:MMTC_BASE_COMPUTING*0.8,RESOURCES[2]:MMTC_BASE_BAND*0.8}
INP_RESOURCES = {RESOURCES[0]:INP_STORAGE, RESOURCES[1]:INP_COMPUTING, RESOURCES[2]:INP_BAND}
